# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Recliq < Formula
  desc "Recall shell commands using natural language"
  homepage "https://recliq.dev"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://pub-cf65b388d51b406b82f97a63b2164b2a.r2.dev/0.1.0/recliq_0.1.0_darwin_amd64.tar.gz"
      sha256 "37cd660fd56fccc45adb644353f0ff02feb7a00a880805022e3ce43096a3ecfe"

      define_method(:install) do
        bin.install "recliq"
      end
    end
    if Hardware::CPU.arm?
      url "https://pub-cf65b388d51b406b82f97a63b2164b2a.r2.dev/0.1.0/recliq_0.1.0_darwin_arm64.tar.gz"
      sha256 "6d7e29e38a699dbde759e067a183e58550c2f1fb049036927017f6798ec1c54d"

      define_method(:install) do
        bin.install "recliq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://pub-cf65b388d51b406b82f97a63b2164b2a.r2.dev/0.1.0/recliq_0.1.0_linux_amd64.tar.gz"
      sha256 "80850ddf6263d9273a38ebdd3c31339fd1366a8e0d7c17dd0e6b3b60d73db30e"
      define_method(:install) do
        bin.install "recliq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://pub-cf65b388d51b406b82f97a63b2164b2a.r2.dev/0.1.0/recliq_0.1.0_linux_arm64.tar.gz"
      sha256 "8c4e568d7fc7d9f7e5bd0ccf3887a3ce860d16bd558b1ad842b690fc30888131"
      define_method(:install) do
        bin.install "recliq"
      end
    end
  end

  test do
    system "#{bin}/recliq", "--version"
  end
end
