# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Recliq < Formula
  desc "Recall shell commands using natural language"
  homepage "https://recliq.dev"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://pub-cf65b388d51b406b82f97a63b2164b2a.r2.dev/0.1.0/recliq_0.1.0_darwin_amd64.tar.gz"
      sha256 "e2a1fe13a6333c235be562524985f1abfc7773b6f98b04e3b6c9241beb2cf4da"

      define_method(:install) do
        bin.install "recliq"
      end
    end
    if Hardware::CPU.arm?
      url "https://pub-cf65b388d51b406b82f97a63b2164b2a.r2.dev/0.1.0/recliq_0.1.0_darwin_arm64.tar.gz"
      sha256 "e79e1058e4068f90d4a55502b834215581d280570af3a1ceb84944fd22066597"

      define_method(:install) do
        bin.install "recliq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://pub-cf65b388d51b406b82f97a63b2164b2a.r2.dev/0.1.0/recliq_0.1.0_linux_amd64.tar.gz"
      sha256 "c5db0c684d989d58b5c541457554f13779d5aad2dffc3fcf057bddab79502652"
      define_method(:install) do
        bin.install "recliq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://pub-cf65b388d51b406b82f97a63b2164b2a.r2.dev/0.1.0/recliq_0.1.0_linux_arm64.tar.gz"
      sha256 "41ccdcb182e456dd68ddba18d729cedcc2cf5e3f2aa27bec12acd1a404892cbd"
      define_method(:install) do
        bin.install "recliq"
      end
    end
  end

  test do
    system "#{bin}/recliq", "--version"
  end
end
