# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Recliq < Formula
  desc "Recall shell commands using natural language"
  homepage "https://recliq.dev"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://pub-cf65b388d51b406b82f97a63b2164b2a.r2.dev/0.4.0/recliq_0.4.0_darwin_amd64.tar.gz"
      sha256 "1ea7888d4a38be9022ff15e19f0e662030924bdaf5a3e6402f59aee704126131"

      define_method(:install) do
        bin.install "recliq"
      end
    end
    if Hardware::CPU.arm?
      url "https://pub-cf65b388d51b406b82f97a63b2164b2a.r2.dev/0.4.0/recliq_0.4.0_darwin_arm64.tar.gz"
      sha256 "dfb1e2e1225024a3d734106ed126cbdba8da5f6047245513ea775466ea5b034b"

      define_method(:install) do
        bin.install "recliq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://pub-cf65b388d51b406b82f97a63b2164b2a.r2.dev/0.4.0/recliq_0.4.0_linux_amd64.tar.gz"
      sha256 "c0c42b74a35698786545ae6a0a9488cc4c734cf8571fa9440a20172f8cdcf734"
      define_method(:install) do
        bin.install "recliq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://pub-cf65b388d51b406b82f97a63b2164b2a.r2.dev/0.4.0/recliq_0.4.0_linux_arm64.tar.gz"
      sha256 "0b0d4013831871f35ccb0dc812e9b4d9955878fb73156e00539e5ca4849abfbe"
      define_method(:install) do
        bin.install "recliq"
      end
    end
  end

  test do
    system "#{bin}/recliq", "--version"
  end
end
