# This file was generated by GoReleaser. DO NOT EDIT.
cask "recliq" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/sareepattamannil/recliq/releases/download/v#{version}/recliq_#{version}_darwin_amd64.tar.gz"
      sha256 "0588d91136c27b1e7433e27f114f2e7e6ba01995caea4bee1c3789c6a2655a7e"
    end
    on_arm do
      url "https://github.com/sareepattamannil/recliq/releases/download/v#{version}/recliq_#{version}_darwin_arm64.tar.gz"
      sha256 "478852c07d294a5b6b1112672b9acbb6a481a091cb59a09c86d2e01cff1588cd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sareepattamannil/recliq/releases/download/v#{version}/recliq_#{version}_linux_amd64.tar.gz"
      sha256 "03205f22c5a116c66ed30e9013657474618d1d593c950bbd20a6538147c57df5"
    end
    on_arm do
      url "https://github.com/sareepattamannil/recliq/releases/download/v#{version}/recliq_#{version}_linux_arm64.tar.gz"
      sha256 "0d70e5f99ff67618b702b1f6ae4ad59dd7e311dd23557a5af4228aa6462317da"
    end
  end

  name "recliq"
  desc "Recall shell commands using natural language"
  homepage "https://recliq.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "recliq"

  # No zap stanza required

end
